Fix `forceCanvas = false` will cause `TypeError: context.fillRect is not a function` because gl.getContextAttributes not exist in @flyskywhy/react-native-gcanvas@5.1.1 then cause isWebGLSupported() in pixi.js v4.8.9/lib/core/utils/index.js return false